// Generated by nuxt-seo-utils
declare module '#app' {
  import { HeadEntry, HeadTag } from '@unhead/vue/types'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}
declare module '@unhead/schema' {

  type PublicFiles = '/ads.txt' | '/bec4b6ad13fe452b8e155aa73081092a.txt' | '/content-types.json' | '/favicon.ico' | '/google4d35b1e02e030dba.html' | '/graph.json' | '/yandex_bb3e8063889348fb.html' | (string & Record<never, never>)
  type JsFiles = (string & Record<never, never>)

  interface SchemaAugmentations {
    link: import('@unhead/schema').UserTagConfigWithoutInnerContent & {
      href: PublicFiles
    }
    script: import('@unhead/schema').TagUserProperties & {
      src: JsFiles
    }
  }
}

export {}
